version: '3.1'

services:
  php:
    image: php:7.4-apache
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/
      - ./docker/docker-php.conf:/etc/apache2/conf-available/docker-php.conf