version: '3'

services:
  php:
    build: ./.docker/php/
    ports:
      - 80:80
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - .:/var/www/html
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      - ./.docker/php/conf.d/docker-php.conf:/etc/apache2/conf-available/docker-php.conf