version: '3.8'

name: php

services:
    php:
        container_name: php
        build:
            context: .
            dockerfile: php/Dockerfile
        
        environment:
            XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
        
        volumes:
            - ../..:/workspaces/PHP
            - ../src:/var/www/html 
        
        ports:
            - 80:80

        # Overrides default command so things don't shut down after the process ends.
        # command: sleep infinity
        
        # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
        # network_mode: service:db
    
    db:
        container_name: db

        build: 
            context: .
            dockerfile: mysql/Dockerfile

        restart: always

        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: jose
            MYSQL_PASSWORD: josefa

        hostname: db

        ports:
            - 3306:3306
            - 33060:33060

        volumes:
            - db_data:/var/lib/mysql
    

    phpmyadmin:
        container_name: phpmyadmin

        image: phpmyadmin:latest

        restart: always
        
        ports:
            - 8080:80

volumes:
    db_data: